---
- hosts: localhost
  become: yes
  vars:
    nextcloud_container_name: nextcloud-aio-mastercontainer
    nextcloud_image: nextcloud/all-in-one:latest
    cloudflare_tunnel_name: nextcloud
    cloudflare_tunnel_credentials_file: "/home/{{ ansible_user }}/.cloudflared/{{ cloudflare_tunnel_name }}.json"
    cloudflare_tunnel_config_file: "/home/{{ ansible_user }}/.cloudflared/config.yml"
    cloudflare_domain: "nextcloud.shadowlabs.cc"

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Nextcloud All-in-One Docker image
      docker_image:
        name: "{{ nextcloud_image }}"
        tag: latest
        source: pull

    - name: Run Nextcloud AIO container
      docker_container:
        name: "{{ nextcloud_container_name }}"
        image: "{{ nextcloud_image }}"
        restart_policy: always
        published_ports:
          - "80:80"
          - "8080:8080"
          - "8443:8443"
        volumes:
          - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
          - /var/run/docker.sock:/var/run/docker.sock:ro

    - name: Install cloudflared
      apt:
        name: cloudflared
        state: present

    - name: Authenticate Cloudflare Tunnel
      command: cloudflared tunnel login
      register: cloudflare_login
      changed_when: cloudflare_login.rc != 0

    - name: Create Cloudflare Tunnel
      command: cloudflared tunnel create {{ cloudflare_tunnel_name }}
      register: cloudflare_tunnel
      changed_when: cloudflare_tunnel.rc != 0

    - name: Create Cloudflare Tunnel Configuration
      copy:
        dest: "{{ cloudflare_tunnel_config_file }}"
        content: |
          tunnel: {{ cloudflare_tunnel.stdout }}
          credentials-file: {{ cloudflare_tunnel_credentials_file }}

          ingress:
            - hostname: {{ cloudflare_domain }}
              service: http://localhost:8080
            - service: http_status:404

    - name: Start Cloudflare Tunnel
      command: cloudflared tunnel run {{ cloudflare_tunnel_name }}
      async: 10
      poll: 0

    - name: Open necessary ports on the firewall
      ufw:
        rule: allow
        name: "Open ports for Nextcloud and Cloudflare Tunnel"
        port: 
          - 80
          - 8080
          - 8443
          - 3478
          - "3478/udp"
      when: ansible_os_family == "Debian"

# Post-Execution Instructions
- name: Post-Execution Instructions
  hosts: localhost
  tasks:
    - name: Display post-execution instructions
      debug:
        msg: |
          The playbook has completed successfully. Please follow these steps to finalize the setup:
          1. Verify that the Nextcloud container is running by executing: docker ps
          2. Access Nextcloud in your browser at http://localhost:8080
          3. Complete the Nextcloud setup wizard in your browser.
          4. Verify that the Cloudflare Tunnel is running by executing: cloudflared tunnel list
          5. Ensure that your domain (nextcloud.shadowlabs.cc) is correctly pointing to your Cloudflare Tunnel.
          6. If you encounter any issues, check the logs for Docker and Cloudflare Tunnel for troubleshooting.