---
- hosts: localhost
  become: yes
  vars:
    nextcloud_container_name: nextcloud-aio-mastercontainer
    nextcloud_image: nextcloud/all-in-one:latest

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Nextcloud All-in-One Docker image
      docker_image:
        name: "{{ nextcloud_image }}"
        tag: latest
        source: pull

    - name: Run Nextcloud AIO container
      docker_container:
        name: "{{ nextcloud_container_name }}"
        image: "{{ nextcloud_image }}"
        restart_policy: always
        published_ports:
          - "80:80"
          - "8080:8080"
          - "8443:8443"
        volumes:
          - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
          - /var/run/docker.sock:/var/run/docker.sock:ro

    - name: Open port 80 on the firewall
      ufw:
        rule: allow
        port: 80
        proto: tcp
      when: ansible_os_family == "Debian"

    - name: Open port 8080 on the firewall
      ufw:
        rule: allow
        port: 8080
        proto: tcp
      when: ansible_os_family == "Debian"

    - name: Open port 8443 on the firewall
      ufw:
        rule: allow
        port: 8443
        proto: tcp
      when: ansible_os_family == "Debian"

# Post-Execution Instructions
- name: Post-Execution Instructions
  hosts: localhost
  tasks:
    - name: Display post-execution instructions
      debug:
        msg: |
          The playbook has completed successfully. Please follow these steps to finalize the setup:
          1. Verify that the Nextcloud container is running by executing: docker ps
          2. Access Nextcloud in your browser at http://localhost:8080
          3. Complete the Nextcloud setup wizard in your browser.
          4. If you encounter any issues, check the logs for Docker for troubleshooting.